//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewLabels() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_Project.Resources.ViewLabels", typeof(ViewLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I forgot my password.
        /// </summary>
        public static string AUTH_LOGIN_RECOVERPASS {
            get {
                return ResourceManager.GetString("AUTH_LOGIN_RECOVERPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access.
        /// </summary>
        public static string AUTH_LOGIN_SUBMIT {
            get {
                return ResourceManager.GetString("AUTH_LOGIN_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string AUTH_LOGIN_TITLE {
            get {
                return ResourceManager.GetString("AUTH_LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        public static string AUTH_LOGOUT {
            get {
                return ResourceManager.GetString("AUTH_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean.
        /// </summary>
        public static string CLEAN {
            get {
                return ResourceManager.GetString("CLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm new password.
        /// </summary>
        public static string CONFIRM_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("CONFIRM_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to Template Project.
        /// </summary>
        public static string HOME_TITLE {
            get {
                return ResourceManager.GetString("HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean.
        /// </summary>
        public static string LABEL_CLEAN {
            get {
                return ResourceManager.GetString("LABEL_CLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Results.
        /// </summary>
        public static string LABEL_RESULTS {
            get {
                return ResourceManager.GetString("LABEL_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string LABEL_SEARCH {
            get {
                return ResourceManager.GetString("LABEL_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalogs.
        /// </summary>
        public static string MODULE_CATALOGS {
            get {
                return ResourceManager.GetString("MODULE_CATALOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboards.
        /// </summary>
        public static string MODULE_DASHBOARDS {
            get {
                return ResourceManager.GetString("MODULE_DASHBOARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Management.
        /// </summary>
        public static string MODULE_MANAGEMENT {
            get {
                return ResourceManager.GetString("MODULE_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payments.
        /// </summary>
        public static string MODULE_PAYMENTS {
            get {
                return ResourceManager.GetString("MODULE_PAYMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reports.
        /// </summary>
        public static string MODULE_REPORTS {
            get {
                return ResourceManager.GetString("MODULE_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string NEW_PASSWORD {
            get {
                return ResourceManager.GetString("NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password will expire in {0} days.
        /// </summary>
        public static string PASSWORD_EXPIRATION_MESSAGE {
            get {
                return ResourceManager.GetString("PASSWORD_EXPIRATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or Email.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or Email is required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Username or Email is required.
        /// </summary>
        public static string MODULE_CONFIGURATION
        {
            get
            {
                return ResourceManager.GetString("MODULE_CONFIGURATION", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a clientes.
        /// </summary>
        public static string MODULE_CUSTOMERS
        {
            get
            {
                return ResourceManager.GetString("MODULE_CUSTOMERS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a proveedores.
        /// </summary>
        public static string MODULE_PROVIDERS
        {
            get
            {
                return ResourceManager.GetString("MODULE_PROVIDERS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a BANCOS.
        /// </summary>
        public static string MODULE_BANKS
        {
            get
            {
                return ResourceManager.GetString("MODULE_BANKS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ALIANZAS Y DESCUENTOS.
        /// </summary>
        public static string MODULE_ALLIANCE_DISCOUNT
        {
            get
            {
                return ResourceManager.GetString("MODULE_ALLIANCE_DISCOUNT", resourceCulture);
            }
        }        

        /// <summary>
        ///   Busca una cadena traducida similar a PLANES.
        /// </summary>
        public static string MODULE_PLANS
        {
            get
            {
                return ResourceManager.GetString("MODULE_PLANS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PLANES.
        /// </summary>
        public static string MODULE_QUOTATION
        {
            get
            {
                return ResourceManager.GetString("MODULE_QUOTATION", resourceCulture);
            }
        }
        
    }
}
